name: example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ente_crypto_dart:
    path: ../
  integration_test:
    sdk: flutter
  flutter_sodium:
  computer:
  logging:
  device_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  ffi: ^2.1.0

flutter:
  uses-material-design: true
